---
- hosts: build_node
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Clone the repository
      git:
        repo: 'https://github.com/AAM-ITV/exam.git'
        dest: /home/jenkins/project

    - name: Build Docker image
      shell: |
         docker build -t aamitv/myapp:latest /home/jenkins/project

    - name: Login to Docker Hub
      shell: |
        echo "your_dockerhub-password" | docker login -u "your_docker-login" --password-stdin
      no_log: true

    - name: Push Docker image to Docker Hub
      shell: |
        docker push aamitv/myapp:latest
